export type TranscriptExchange = { speaker: "Dispatcher" | "Caller"; text: string };
export type EmergencyContact = { name: string; relationship: string; phone: string };
export type NotesSummary = {
  chiefComplaint: string;
  vitals?: string;
  patientHistory: string;
  currentMedications: string;
  allergies: string;
  callerRelationship: string;
  keyObservations: string;
  priority: string;
};
export type Patient = {
  id: string;
  name: string;
  age?: number;
  sex?: "M" | "F";
  dob?: string;
  patientId?: string;
  phone?: string;
  address?: string;
  email?: string;
  language: string;
  risk: "HIGH" | "MED" | "LOW" | "UNK";
  chiefComplaint: string;
  conditions: string[];
  medications: string[];
  allergies: string[];
  avatar: string;
  avatarBg: string;
  emergencyContact?: EmergencyContact;
  hasFullData: boolean;
  note?: string;
  transcriptExchanges: TranscriptExchange[];
  notesSummary: NotesSummary;
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "stroke",
    name: "Elena Nakamura",
    age: 71, sex: "F", dob: "04/22/1953",
    patientId: "PT-SF240001",
    phone: "(415) 555-0182",
    address: "742 Lombard St, San Francisco CA 94133",
    email: "e.nakamura@email.com",
    language: "English/Japanese",
    risk: "HIGH",
    chiefComplaint: "Suspected Stroke",
    conditions: ["Atrial Fibrillation", "Hypertension", "Type 2 Diabetes"],
    medications: ["Warfarin 5mg", "Lisinopril 10mg", "Metformin 500mg"],
    allergies: ["Penicillin"],
    avatar: "EN", avatarBg: "bg-blue-600",
    emergencyContact: { name: "Yuki Nakamura", relationship: "Daughter", phone: "(415) 555-0291" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "I... something is wrong with my face. I'm having trouble speaking. My left arm won't move." },
      { speaker: "Dispatcher", text: "Ma'am, stay calm. What is your address?" },
      { speaker: "Caller", text: "Seven forty-two Lombard Street, San Francisco. I'm alone." },
      { speaker: "Dispatcher", text: "How long have you had these symptoms?" },
      { speaker: "Caller", text: "Maybe fifteen minutes. I was eating breakfast and my arm just fell. My face feels droopy." },
      { speaker: "Dispatcher", text: "Are you on any blood thinners or medications?" },
      { speaker: "Caller", text: "Yes. Warfarin, for atrial fibrillation. And lisinopril, metformin. I'm allergic to penicillin." },
      { speaker: "Dispatcher", text: "Very important information. Do not try to drive. If it is safe, can you unlock your front door?" },
      { speaker: "Caller", text: "I'll try. Please hurry. I'm scared." },
      { speaker: "Dispatcher", text: "You are doing great. Unit 12 is dispatched to 742 Lombard St. ETA 5 minutes. Stay on the line." },
      { speaker: "Caller", text: "Thank you. My daughter's number is... in my phone. Yuki." },
    ],
    notesSummary: {
      chiefComplaint: "Suspected stroke - left facial droop, left arm weakness, slurred speech, onset ~15 min",
      vitals: "GCS estimated 13-14 at call; symptoms acute onset during breakfast",
      patientHistory: "Atrial Fibrillation, Hypertension, Type 2 Diabetes",
      currentMedications: "Warfarin 5mg (CRITICAL - anticoagulant, impacts tPA eligibility), Lisinopril 10mg, Metformin 500mg",
      allergies: "Penicillin",
      callerRelationship: "Patient (self-reporting)",
      keyObservations: "Patient home alone. Speech impaired but coherent enough to provide history. Warfarin use must be communicated to receiving neurologist immediately. Activate stroke protocol and pre-alert ED.",
      priority: "HIGH - Activate stroke protocol, pre-alert ED neurology",
    },
  },
  {
    id: "chest",
    name: "Marcus Webb",
    age: 58, sex: "M", dob: "11/08/1965",
    patientId: "PT-OAK240002",
    phone: "(510) 555-0347",
    address: "3820 Telegraph Ave, Oakland CA 94609",
    email: "m.webb@email.com",
    language: "English",
    risk: "HIGH",
    chiefComplaint: "Acute Chest Pain",
    conditions: ["Hypertension", "Hyperlipidemia", "Former Smoker"],
    medications: ["Atorvastatin 40mg", "Amlodipine 5mg", "Aspirin 81mg daily"],
    allergies: ["Sulfa drugs"],
    avatar: "MW", avatarBg: "bg-red-600",
    emergencyContact: { name: "Denise Webb", relationship: "Wife", phone: "(510) 555-0412" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "My husband is having a heart attack. He's clutching his chest, sweating terribly, and his skin has gone gray." },
      { speaker: "Dispatcher", text: "What is your address?" },
      { speaker: "Caller", text: "3820 Telegraph Avenue in Oakland. Please hurry." },
      { speaker: "Dispatcher", text: "How long has he had the chest pain and is it going anywhere else?" },
      { speaker: "Caller", text: "It started about 20 minutes ago. He says it feels like someone sitting on his chest, and it's going into his left arm." },
      { speaker: "Dispatcher", text: "Is he conscious and breathing? Any prior heart problems?" },
      { speaker: "Caller", text: "He's awake but barely. He had a cardiac scan last year, they said nothing serious. He's on atorvastatin and amlodipine and takes aspirin 81mg daily. He's allergic to sulfa drugs." },
      { speaker: "Dispatcher", text: "Do not give him anything else. Keep him seated and still. Paramedics are 5 minutes away." },
      { speaker: "Caller", text: "Marcus, stay with me. Help is coming. Should I do anything else?" },
      { speaker: "Dispatcher", text: "Keep him calm. Do not let him walk. Unit 7 is en route to 3820 Telegraph Ave, Oakland. ETA 5 minutes. Stay on the line." },
      { speaker: "Caller", text: "Okay. He's breathing but it's labored. Please hurry." },
    ],
    notesSummary: {
      chiefComplaint: "Acute chest pain with left arm radiation, diaphoresis, 20-minute duration",
      vitals: "Diaphoretic, pallor/gray skin tone, labored breathing per caller",
      patientHistory: "Hypertension, Hyperlipidemia, Former Smoker",
      currentMedications: "Atorvastatin 40mg, Amlodipine 5mg, Aspirin 81mg daily",
      allergies: "Sulfa drugs - AVOID all sulfa-containing medications",
      callerRelationship: "Wife (Denise Webb)",
      keyObservations: "Classic STEMI presentation. Patient already on daily aspirin. Do NOT administer additional aspirin. Avoid sulfa medications. Activate cath lab on arrival if 12-lead confirms ST elevation. Cardiac monitor on scene immediately.",
      priority: "HIGH - Possible STEMI, activate cardiac protocol and pre-alert cath lab",
    },
  },
  {
    id: "resp",
    name: "Lucia Reyes",
    age: 76, sex: "F", dob: "07/03/1948",
    patientId: "PT-SJ240003",
    phone: "(408) 555-0261",
    address: "1456 The Alameda, San Jose CA 95126",
    email: "l.reyes@email.com",
    language: "Spanish/English",
    risk: "HIGH",
    chiefComplaint: "Acute Respiratory Distress",
    conditions: ["COPD", "Congestive Heart Failure"],
    medications: ["Furosemide 40mg", "Albuterol inhaler (rescue)", "Tiotropium"],
    allergies: ["Aspirin", "NSAIDs"],
    avatar: "LR", avatarBg: "bg-purple-600",
    emergencyContact: { name: "Carlos Reyes", relationship: "Son", phone: "(408) 555-0389" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "My mother can't breathe. She has COPD and her lips are turning blue. I need help now." },
      { speaker: "Dispatcher", text: "What is your address?" },
      { speaker: "Caller", text: "1456 The Alameda, San Jose." },
      { speaker: "Dispatcher", text: "How long has she been like this and is she on home oxygen?" },
      { speaker: "Caller", text: "It got bad in the last 10 minutes. She has a home concentrator, I put her on 6 liters but the pulse ox only reads 84 now." },
      { speaker: "Dispatcher", text: "Has she used her rescue inhaler?" },
      { speaker: "Caller", text: "Yes, albuterol, twice already. Not helping. She also has congestive heart failure and she takes furosemide. She's allergic to aspirin and NSAIDs - very important." },
      { speaker: "Dispatcher", text: "Keep the oxygen on. Sit her upright, feet down. Do not lay her flat." },
      { speaker: "Caller", text: "She's upright. She can barely speak and she's using her neck muscles to breathe." },
      { speaker: "Dispatcher", text: "ALS Unit 19 is en route to 1456 The Alameda, San Jose. ETA 4 minutes. Is the front door unlocked?" },
      { speaker: "Caller", text: "Yes, I'll leave it open. Please, she's 76 and very scared." },
    ],
    notesSummary: {
      chiefComplaint: "Acute respiratory distress with cyanosis, SpO2 84% on 6L home O2",
      vitals: "SpO2 84% on 6L O2, RR elevated (accessory muscle use), unable to speak in full sentences",
      patientHistory: "COPD, Congestive Heart Failure",
      currentMedications: "Furosemide 40mg, Albuterol rescue inhaler (2 doses given - inadequate response), Tiotropium",
      allergies: "Aspirin - CONTRAINDICATED. NSAIDs - CONTRAINDICATED",
      callerRelationship: "Daughter",
      keyObservations: "Dual diagnosis COPD + CHF complicates treatment. Albuterol ineffective - consider CPAP/BiPAP. Do not use aspirin or NSAIDs under any circumstances. Sitting position maintained. Consider early intubation if SpO2 does not improve.",
      priority: "HIGH - Respiratory failure risk, BiPAP-ready unit preferred",
    },
  },
  {
    id: "diabetic",
    name: "David Park",
    age: 44, sex: "M", dob: "02/17/1980",
    patientId: "PT-FRE240004",
    phone: "(510) 555-0518",
    address: "4200 Mowry Ave Apt 8B, Fremont CA 94538",
    email: "d.park@email.com",
    language: "Korean/English",
    risk: "MED",
    chiefComplaint: "Diabetic Emergency - Hypoglycemia",
    conditions: ["Type 1 Diabetes", "Hypothyroidism"],
    medications: ["Insulin Glargine (taken this morning)", "Levothyroxine 50mcg"],
    allergies: [],
    avatar: "DP", avatarBg: "bg-teal-600",
    emergencyContact: { name: "Ji-yeon Park", relationship: "Wife", phone: "(510) 555-0622" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "I'm a Type 1 diabetic. My sugar is really low - I'm shaking, sweating, and I can't think straight." },
      { speaker: "Dispatcher", text: "What is your address?" },
      { speaker: "Caller", text: "4200 Mowry Avenue, Apartment 8B, Fremont." },
      { speaker: "Dispatcher", text: "Is anyone with you? How long have you felt this way?" },
      { speaker: "Caller", text: "No, I'm alone. About 30 minutes. I took my insulin this morning and then... I forgot to eat. I tried orange juice but I couldn't finish it." },
      { speaker: "Dispatcher", text: "Do not try to stand up. Do you have any glucose tablets or more juice within reach?" },
      { speaker: "Caller", text: "Juice is in the fridge but I don't think I can get up. My legs feel... wrong. Things are starting to spin." },
      { speaker: "Dispatcher", text: "Stay where you are. Any allergies? Other medications besides insulin?" },
      { speaker: "Caller", text: "No allergies. Levothyroxine for my thyroid. My wife Ji-yeon's number... is in my phone if you need it." },
      { speaker: "Dispatcher", text: "ALS Unit 3 dispatched to 4200 Mowry Ave Apt 8B, Fremont. ETA 4 minutes. Stay on the line and keep talking." },
      { speaker: "Caller", text: "Okay... I'm still here. Hurry, please." },
    ],
    notesSummary: {
      chiefComplaint: "Suspected hypoglycemia - Type 1 diabetic, long-acting insulin taken, meal skipped",
      vitals: "Shaking, diaphoretic, progressive cognitive decline during call, legs weak",
      patientHistory: "Type 1 Diabetes, Hypothyroidism",
      currentMedications: "Insulin Glargine (taken this AM - long-acting), Levothyroxine 50mcg",
      allergies: "NKDA",
      callerRelationship: "Patient (self-reporting, cognitive decline noted during call)",
      keyObservations: "Patient took long-acting insulin and skipped meal. Oral glucose attempt failed. Progressive mental status change during call suggests moderate-to-severe hypoglycemia. D50 IV or glucagon IM likely needed. Notify wife Ji-yeon at (510) 555-0622.",
      priority: "MEDIUM - Hypoglycemic emergency, D50 or glucagon anticipated",
    },
  },
  {
    id: "trauma",
    name: "Sofia Russo",
    age: 29, sex: "F", dob: "09/14/1994",
    patientId: "PT-BRK240005",
    phone: "(510) 555-0743",
    address: "2315 Durant Ave, Berkeley CA 94704",
    email: "s.russo@email.com",
    language: "English",
    risk: "MED",
    chiefComplaint: "Blunt Trauma - MVA",
    conditions: [],
    medications: [],
    allergies: ["Latex"],
    avatar: "SR", avatarBg: "bg-orange-600",
    emergencyContact: { name: "Tony Russo", relationship: "Father", phone: "(415) 555-0891" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "I just saw a bad T-bone accident at University and MLK in Berkeley. A car ran a red and hit a silver sedan. The woman driver isn't moving right." },
      { speaker: "Dispatcher", text: "Is she conscious? Any visible injuries?" },
      { speaker: "Caller", text: "She's awake and crying. She can't move her right arm and the airbag went off. Her door is crumpled in on her side." },
      { speaker: "Dispatcher", text: "Do not move her. Did she lose consciousness at any point after impact?" },
      { speaker: "Caller", text: "She was dazed for about a minute right after. She told me her name is Sofia and she asked about her dad." },
      { speaker: "Dispatcher", text: "Do not touch her neck or head. Is the scene safe? Has traffic stopped?" },
      { speaker: "Caller", text: "I turned on my hazards. People have stopped. The other driver seems okay. Sofia said she's allergic to latex when I mentioned a first aid kit." },
      { speaker: "Dispatcher", text: "Important, noted. Two units are en route. Estimated arrival 5 minutes. Keep her calm and still." },
      { speaker: "Caller", text: "Got it. She's asking about her car but I'm keeping her focused on breathing." },
      { speaker: "Dispatcher", text: "Units 22 and 31 dispatched to University Ave and MLK Jr Way, Berkeley. Traffic control notified. ETA 5 minutes." },
      { speaker: "Caller", text: "Okay, we're here. She's alert but in real pain with that arm." },
    ],
    notesSummary: {
      chiefComplaint: "Blunt trauma from T-bone MVA - right arm immobility, brief post-impact LOC, airbag deployment",
      vitals: "Conscious and oriented; brief LOC immediately post-impact (~1 min)",
      patientHistory: "No known prior medical conditions",
      currentMedications: "None reported",
      allergies: "Latex - ALL EQUIPMENT MUST BE LATEX-FREE",
      callerRelationship: "Bystander (witnessed accident)",
      keyObservations: "Restrained driver, high-speed right-angle impact. Door intrusion noted - possible extrication needed. C-spine precautions mandatory. Right arm deformity/immobility - likely fracture. Brief LOC indicates concussive injury. Use only latex-free gloves and equipment.",
      priority: "MEDIUM - Trauma with C-spine concern, extrication may be required",
    },
  },
  {
    id: "fall",
    name: "James O'Brien",
    age: 82, sex: "M", dob: "06/12/1941",
    patientId: "PT-PAL240006",
    phone: "(650) 555-0124",
    address: "789 Hamilton Ave, Palo Alto CA 94301",
    email: "j.obrien@email.com",
    language: "English",
    risk: "LOW",
    chiefComplaint: "Elderly Fall",
    conditions: ["Parkinson's Disease", "Osteoporosis", "Hypertension"],
    medications: ["Carbidopa/Levodopa 25/100mg", "Alendronate 70mg", "Lisinopril 5mg"],
    allergies: ["Codeine"],
    avatar: "JO", avatarBg: "bg-gray-600",
    emergencyContact: { name: "Maureen O'Brien", relationship: "Daughter", phone: "(650) 555-0287" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "My neighbor Mr. O'Brien fell in his living room. He's 82 and has Parkinson's. I can hear him calling through the door." },
      { speaker: "Dispatcher", text: "What is the address?" },
      { speaker: "Caller", text: "789 Hamilton Avenue in Palo Alto. I have a spare key - should I go in?" },
      { speaker: "Dispatcher", text: "Yes, please enter carefully. Do not move him until you assess what is injured." },
      { speaker: "Caller", text: "I'm inside now. He's near the coffee table. There's a cut on his forehead and he's holding his left hip. He says he can't put weight on that leg." },
      { speaker: "Dispatcher", text: "Do not try to help him stand. Did he lose consciousness at any point?" },
      { speaker: "Caller", text: "He says no. He has Parkinson's and osteoporosis - his daughter told me. And I know he's allergic to codeine, he has a bracelet that says so." },
      { speaker: "Dispatcher", text: "Excellent observation. Does he take any blood thinners?" },
      { speaker: "Caller", text: "I'm not sure about that. He mentioned Parkinson's medication and a bone pill. He seems alert but he's in a lot of pain." },
      { speaker: "Dispatcher", text: "Keep him warm and still. BLS Unit 14 dispatched to 789 Hamilton Ave, Palo Alto. ETA 5 minutes." },
      { speaker: "Caller", text: "The door is open and I'll flag them down. He's alert and talking to me." },
    ],
    notesSummary: {
      chiefComplaint: "Elderly fall with left hip pain, unable to bear weight, minor head laceration",
      vitals: "Conscious and alert, in pain, no LOC reported",
      patientHistory: "Parkinson's Disease, Osteoporosis, Hypertension",
      currentMedications: "Carbidopa/Levodopa 25/100mg, Alendronate 70mg (bisphosphonate for osteoporosis), Lisinopril 5mg",
      allergies: "Codeine - CONTRAINDICATED. Medical alert bracelet confirmed.",
      callerRelationship: "Neighbor (has spare key, gained access)",
      keyObservations: "High fall-risk due to Parkinson's. Osteoporosis significantly increases hip fracture probability. Head laceration present - assess for anticoagulant use. Pain management must avoid codeine - consider ketorolac (no NSAID allergy noted) or low-dose morphine. Daughter Maureen at (650) 555-0287.",
      priority: "LOW - Stable, suspected left hip fracture, pain management needed",
    },
  },
  {
    id: "pediatric",
    name: "Zoe Coleman",
    age: 6, sex: "F", dob: "03/20/2018",
    patientId: "PT-SF240007",
    phone: "(415) 555-0956",
    address: "2100 Jackson St, San Francisco CA 94115",
    email: "k.coleman@email.com",
    language: "English",
    risk: "LOW",
    chiefComplaint: "Pediatric Emergency - Febrile Seizure",
    conditions: ["Febrile Seizure History"],
    medications: ["Diazepam rectal 2.5mg PRN (prescribed)"],
    allergies: ["Amoxicillin (hives)"],
    avatar: "ZC", avatarBg: "bg-pink-500",
    emergencyContact: { name: "Amara Coleman", relationship: "Mother", phone: "(415) 555-0956" },
    hasFullData: true,
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "My daughter is having a seizure! She's 6 years old and she's shaking and won't respond to me!" },
      { speaker: "Dispatcher", text: "Stay calm. What is your address?" },
      { speaker: "Caller", text: "2100 Jackson Street, San Francisco. Please hurry." },
      { speaker: "Dispatcher", text: "Is this her first seizure? Is she breathing?" },
      { speaker: "Caller", text: "No, she has febrile seizures - she's had them before with high fever. This one is already 3 minutes. Yes she's breathing. Her fever was 104.1 before this." },
      { speaker: "Dispatcher", text: "Turn her on her side right now. Do NOT put anything in her mouth. Is she on her side?" },
      { speaker: "Caller", text: "Yes, she's on her side. She has prescribed rectal diazepam at home - 2.5mg. Should I give it?" },
      { speaker: "Dispatcher", text: "If the seizure passes 5 minutes, follow the label dosage. Any allergies?" },
      { speaker: "Caller", text: "Amoxicillin - she got hives last year. That's the only one we know of. The shaking is slowing down... I think it's stopping." },
      { speaker: "Dispatcher", text: "Good. Even so she must be evaluated. Unit 8 dispatched to 2100 Jackson St, San Francisco. ETA 3 minutes. Stay on the line." },
      { speaker: "Caller", text: "She stopped. She's breathing but limp and very confused. Kenji, her dad, is calling her name." },
    ],
    notesSummary: {
      chiefComplaint: "Pediatric febrile seizure, age 6, fever 104.1F, duration approximately 3-4 minutes",
      vitals: "Fever 104.1F pre-seizure, seizure self-terminated at approximately 3-4 minutes, post-ictal state at EMS arrival",
      patientHistory: "Known febrile seizure history",
      currentMedications: "Diazepam rectal 2.5mg PRN (prescribed rescue medication at home)",
      allergies: "Amoxicillin (hives) - avoid all penicillin-class antibiotics",
      callerRelationship: "Father (Kenji Coleman)",
      keyObservations: "Seizure appeared self-terminating before rescue diazepam was needed. Confirm with parents if diazepam was administered. Post-ictal evaluation required. Fever management and workup for seizure trigger. Avoid amoxicillin. Mother Amara at (415) 555-0956.",
      priority: "LOW - Likely febrile seizure, self-terminating; full evaluation required",
    },
  },
  {
    id: "unk1",
    name: "Unknown Male, approx 40s",
    sex: "M",
    address: "Near 4th St and Brannan St, San Francisco CA 94107",
    language: "Unknown",
    risk: "UNK",
    chiefComplaint: "Unresponsive - Unknown Cause",
    conditions: [],
    medications: [],
    allergies: [],
    avatar: "UM", avatarBg: "bg-gray-500",
    hasFullData: false,
    note: "No identification available. Good Samaritan found patient unresponsive near waterfront. No wallet, phone, or ID on person. Cannot obtain medical history or consent.",
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "I found a man lying on the sidewalk near the waterfront. He's completely unresponsive. I can't wake him up." },
      { speaker: "Dispatcher", text: "What is the address or nearest cross street?" },
      { speaker: "Caller", text: "Near 4th and Brannan Street in San Francisco, the Embarcadero area." },
      { speaker: "Dispatcher", text: "Is he breathing?" },
      { speaker: "Caller", text: "I think so - his chest is moving slowly. But he won't respond to me at all." },
      { speaker: "Dispatcher", text: "Approximately how old does he appear? Any visible injuries or substances nearby?" },
      { speaker: "Caller", text: "Maybe early 40s. No blood. Dressed normally - jeans and a jacket. No wallet or phone on him. I checked for ID. Nothing." },
      { speaker: "Dispatcher", text: "Do not move him. Does he have a medical alert bracelet or anything identifying?" },
      { speaker: "Caller", text: "Nothing at all. No bracelet, no ID. I have no idea who he is." },
      { speaker: "Dispatcher", text: "You did the right thing calling. ALS Unit 6 en route to 4th and Brannan, San Francisco. ETA 4 minutes. Stay with him." },
      { speaker: "Caller", text: "Okay, I'll stay. His breathing sounds okay but he's completely out. Should I wave down the ambulance?" },
      { speaker: "Dispatcher", text: "Yes - keep the area clear and flag them down. If breathing stops, I will walk you through CPR. Stay on the line." },
    ],
    notesSummary: {
      chiefComplaint: "Unresponsive male found near waterfront, cause unknown",
      vitals: "Slow spontaneous respiration; no response to verbal or tactile stimuli; no visible trauma",
      patientHistory: "Unknown - no identification available",
      currentMedications: "Unknown",
      allergies: "Unknown - treat with caution",
      callerRelationship: "Good Samaritan (unrelated bystander)",
      keyObservations: "No ID, wallet, or phone found. Male, estimated 40s. Rule out: hypoglycemia (BGL on arrival), opioid overdose (naloxone empirically), cardiac arrest, CVA. Cannot obtain informed consent - treat as medical emergency. Law enforcement notified for ID assistance.",
      priority: "UNKNOWN - Treat as high acuity until cause identified",
    },
  },
  {
    id: "unk2",
    name: "Unknown Female, approx 30s",
    sex: "F",
    address: "1600 Market St, San Francisco CA 94102",
    language: "Unknown",
    risk: "UNK",
    chiefComplaint: "Suspected Overdose",
    conditions: [],
    medications: [],
    allergies: [],
    avatar: "UF", avatarBg: "bg-gray-500",
    hasFullData: false,
    note: "Patient found unconscious in coffee shop. No identification present. Used syringe and foil packet observed at scene. Barista has seen patient before but does not know name.",
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "There's a woman collapsed inside a coffee shop. She just fell off her stool and she's unconscious." },
      { speaker: "Dispatcher", text: "What is your address?" },
      { speaker: "Caller", text: "1600 Market Street, San Francisco." },
      { speaker: "Dispatcher", text: "Is she breathing?" },
      { speaker: "Caller", text: "Yes but it's very slow and shallow. Her lips look grayish-blue." },
      { speaker: "Dispatcher", text: "What happened before she fell? Did she complain of anything?" },
      { speaker: "Caller", text: "She was sitting alone, nodding off. She didn't seem well and then she just fell. There's a small bag near her with a used syringe and some foil." },
      { speaker: "Dispatcher", text: "Do not touch those items. Does she have any identification?" },
      { speaker: "Caller", text: "No wallet, no ID, no phone visible. The barista has seen her before but doesn't know her name." },
      { speaker: "Dispatcher", text: "Turn her on her side carefully if she is not already. Has anyone at the location administered Narcan?" },
      { speaker: "Caller", text: "No, no one has Narcan. She's on her side now. Her breathing sounds really bad." },
      { speaker: "Dispatcher", text: "ALS Unit 18 is en route with naloxone. ETA 3 minutes. Do not leave her side. Keep the area around her clear and do not touch the drug paraphernalia." },
      { speaker: "Caller", text: "Understood. She's still breathing. Hurry please." },
    ],
    notesSummary: {
      chiefComplaint: "Suspected opioid overdose - unconscious female in coffee shop, cyanotic lips",
      vitals: "Slow shallow respirations, cyanotic lips, unresponsive",
      patientHistory: "Unknown - no identification available",
      currentMedications: "Unknown",
      allergies: "Unknown",
      callerRelationship: "Bystander (coffee shop patron)",
      keyObservations: "Used syringe and foil packaging at scene consistent with IV drug use. Respiratory depression and cyanosis strongly suggest opioid overdose. Administer naloxone (Narcan) on arrival. No ID found. Scene items preserved - do not disturb. Barista is a repeat witness but cannot identify patient. Law enforcement notified.",
      priority: "UNKNOWN - Suspected opioid overdose, respiratory compromise, naloxone indicated",
    },
  },
  {
    id: "unk3",
    name: "Unknown Male, approx 20s",
    sex: "M",
    address: "Near 16th St and Mission St, San Francisco CA 94103",
    language: "Unknown",
    risk: "UNK",
    chiefComplaint: "Good Samaritan - Unidentified Person",
    conditions: [],
    medications: [],
    allergies: [],
    avatar: "UM", avatarBg: "bg-gray-400",
    hasFullData: false,
    note: "Individual found slumped outside 16th/Mission BART station. Unresponsive, no identification on person. Oxycodone bottle and unlabeled pill bottle found in open backpack at scene.",
    transcriptExchanges: [
      { speaker: "Dispatcher", text: "911, what is your emergency?" },
      { speaker: "Caller", text: "There's a young guy slumped against the wall outside the 16th Street BART station. I can't tell if he's asleep or something is seriously wrong." },
      { speaker: "Dispatcher", text: "What is the exact location?" },
      { speaker: "Caller", text: "16th and Mission Street, San Francisco, right outside the BART entrance on Mission side." },
      { speaker: "Dispatcher", text: "Can you approach him and tell me if he is breathing?" },
      { speaker: "Caller", text: "I'm going closer now. Yes he's breathing but it sounds like gurgling. Maybe early 20s. He has a backpack that's open with stuff scattered." },
      { speaker: "Dispatcher", text: "The gurgling sound is important. Try tapping his shoulder firmly. Does he respond?" },
      { speaker: "Caller", text: "Not at all. He's completely out. There are pill bottles near the bag - one says oxycodone and one is empty with no label." },
      { speaker: "Dispatcher", text: "Do not touch the bottles. Does he have any identification on him?" },
      { speaker: "Caller", text: "No wallet, nothing in his pockets. No ID at all. A couple other people are around and someone else might be calling too." },
      { speaker: "Dispatcher", text: "ALS Unit 21 dispatched to 16th and Mission, San Francisco. ETA 3 minutes. Tilt his head back slightly to open his airway. Do you see his chest still moving?" },
      { speaker: "Caller", text: "Yes, barely. The gurgling is still there. Please hurry." },
      { speaker: "Dispatcher", text: "Help is very close. Stay on the line. If breathing stops, I will guide you through CPR." },
    ],
    notesSummary: {
      chiefComplaint: "Unresponsive young male outside BART station, gurgling respirations, pill bottles at scene",
      vitals: "Gurgling respirations indicating possible airway compromise, unresponsive to stimuli",
      patientHistory: "Unknown",
      currentMedications: "Oxycodone bottle found at scene; second unlabeled bottle",
      allergies: "Unknown",
      callerRelationship: "Good Samaritan bystander",
      keyObservations: "Gurgling respirations suggest partial airway obstruction or fluid. Oxycodone and unlabeled pills at scene suggest polypharmacy overdose. Airway management is priority 1. Consider naloxone empirically. No identification. Law enforcement also notified per scene items. Scene preservation important.",
      priority: "UNKNOWN - Possible overdose, airway compromise, naloxone and airway management priority",
    },
  },
];
